import Head from 'next/head'
import Footer from '../components/Footer';
import dynamic from 'next/dynamic';
import React from "react";
import { Alert } from '../components/alert.jsx';
import { ContractFactory } from 'ethers';

const Header = dynamic(() => import('../components/Header'), {
    ssr: false,
})

export default function Create() {

    //deploy factory.
    const factory = new ContractFactory(contractAbi, contractByteCode);

    const deployMyContract = async () => {
        const contract = await factory.deploy(deployArgs);
        console.log(contract.address);
        console.log(contract.deployTransaction);
    }

    return (
        <div className="min-h-screen bg-white" data-theme="bumblebee">
            <Head>
                <title>Next.js Startup</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />

            <Alert />

            <div className="min-h-screen m-auto ml-10 mt-10">
                <div className="form-control w-full max-w-xs">
                    <label className="label">
                        <span className="label-text">What is your tickets title?</span>
                    </label>
                    <input type="text" placeholder="Type here" className="input input-bordered w-full max-w-xs" />
                </div>

                <div className="form-control w-full max-w-xs  mt-5">
                    <label className="label">
                        <span className="label-text">What is your tickets symbol?</span>
                    </label>
                    <input type="text" placeholder="Type here" className="input input-bordered w-full max-w-xs" />
                </div>

                <div className="form-control w-full max-w-xs  mt-5">
                    <label className="label">
                        <span className="label-text">What is tickets number?</span>
                    </label>
                    <input type="text" placeholder="Type here" className="input input-bordered w-full max-w-xs" />
                </div>

                <div className="form-control w-full max-w-xs mt-5">
                    <label className="label">
                        <span className="label-text">What is your tickets price?</span>
                    </label>
                    <input type="text" placeholder="Type here" className="input input-bordered w-full max-w-xs" />
                </div>

                <div className="form-control w-full max-w-xs">
                    <button className="w-full glass btn mt-10">next</button>
                </div>

            </div>

            <Footer />
        </div >
    )
}
