import Head from 'next/head'
import Footer from '../components/Footer';
import dynamic from 'next/dynamic';
import React from "react";
import { Alert } from '../components/alert.jsx';
import { FaUserAlt, FaPlusSquare, FaListUl, FaAffiliatetheme } from "react-icons/fa";

const Header = dynamic(() => import('../components/Header'), {
  ssr: false,
})

export default function Home() {
  return (
    <div className="min-h-screen" data-theme="wireframe">
      <Head>
        <title>digital ticket stream startup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Alert />

      <div className="hero min-h-screen">
        <div className="hero-content text-center">
          <div className="max-w-md">
            <h1 className="text-5xl font-bold">Hello there</h1>
            <p className="py-6 text-xl font-normal leading-normal mt-0 mb-2">Digital-ticket-stream is a paid video ticketing platform where users can charge tickets from clients by creating NFTs ticket, allow users to subscribe to broadcasting notifications.</p>
            <button className="btn">
              <FaListUl size="1rem" />
              Explore
            </button>
            <button className="btn mx-5">
              <FaPlusSquare size="1rem" />
              Create
            </button>
          </div>
        </div>

      </div>

      <Footer />
    </div >
  )
}
