import Head from 'next/head'
import Footer from '../components/Footer';
import dynamic from 'next/dynamic';
import React from "react";
import { Alert } from '../components/alert.jsx';

const Header = dynamic(() => import('../components/Header'), {
    ssr: false,
})

export default function Lists() {
    return (
        <div className="min-h-screen bg-white" data-theme="bumblebee">
            <Head>
                <title>Next.js Startup</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />

            <Alert />

            <div className="min-h-screen bg-base-200">
                <div class="container mx-auto px-5 py-2 lg:px-32 lg:pt-12">
                    <div class="-m-1 flex flex-wrap md:-m-2">
                        <div class="flex w-1/3 flex-wrap cursor-pointer">
                            <div class="w-full p-1 md:p-2">
                                <img
                                    alt="gallery"
                                    class="block h-full w-full rounded-lg object-cover object-center"
                                    src="https://tecdn.b-cdn.net/img/Photos/Horizontal/Nature/4-col/img%20(73).webp" />
                            </div>
                            <div className='m-auto'>
                                title1
                            </div>
                        </div>
                        <div class="flex w-1/3 flex-wrap cursor-pointer">
                            <div class="w-full p-1 md:p-2">
                                <img
                                    alt="gallery"
                                    class="block h-full w-full rounded-lg object-cover object-center"
                                    src="https://tecdn.b-cdn.net/img/Photos/Horizontal/Nature/4-col/img%20(74).webp" />
                            </div>
                            <div className='m-auto'>
                                title1
                            </div>
                        </div>
                        <div class="flex w-1/3 flex-wrap cursor-pointer">
                            <div class="w-full p-1 md:p-2">
                                <img
                                    alt="gallery"
                                    class="block h-full w-full rounded-lg object-cover object-center"
                                    src="https://tecdn.b-cdn.net/img/Photos/Horizontal/Nature/4-col/img%20(75).webp" />
                            </div>
                            <div className='m-auto'>
                                title1
                            </div>
                        </div>

                    </div>
                </div>
            </div>

            <Footer />
        </div >
    )
}
