import Head from 'next/head'
import Footer from '../components/Footer';
import dynamic from 'next/dynamic';
import React from "react";
import { Alert } from '../components/alert.jsx';
import { useState, useEffect } from "react";
import Link from 'next/link';
import { FaUserAlt, FaPlusSquare, FaListUl, FaAffiliatetheme } from "react-icons/fa";

const Header = dynamic(() => import('../components/Header'), {
    ssr: false,
})

export default function Lists() {

    const [lists, setLists] = useState([]);

    const getList = async () => {
        let ret = [];
        for (let i = 0; i < 20; i++) {
            ret.push(i);
        }
        setLists(ret);
    }

    useEffect(() => {
        getList();
    }, [])

    return (
        <div className="min-h-screen bg-white" data-theme="bumblebee">
            <Head>
                <title>streams list</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <Alert />

            <div className="min-h-screen">
                <div className="container mx-auto my-10 px-5 py-2 lg:px-32 lg:pt-12 mb-20">
                    <div className='flex flex-row'>
                        <div className='mt-1'><FaListUl size="2rem" /></div>
                        <div className='mx-2 text-3xl font-bold'>Room List</div>
                    </div>
                    <div className="divider"></div>
                    <div className="-m-1 flex flex-wrap md:-m-2">

                        {lists.map((item, index) => (
                            <Link className='' href="/info">
                                <div className="flex w-1/4 flex-wrap cursor-pointer mt-10">
                                    <div className="w-full p-1 md:p-2">
                                        <img
                                            alt="gallery"
                                            className="block h-full w-full rounded-lg object-cover object-center"
                                            src="https://tecdn.b-cdn.net/img/Photos/Horizontal/Nature/4-col/img%20(73).webp" />
                                    </div>
                                    <div className='flex'>
                                        <div className='flex-none ml-2'>
                                            <img width="30" className="mask mask-circle" src="https://yt3.ggpht.com/TNOytUYxQBFw3ETzlB1OCeCyqYkNxEJZxRO2xAa5CXjK-Fb9bGw3BLV3Z-IwRFE2Kl1vleN9=s68-c-k-c0x00ffffff-no-rj" />
                                        </div>

                                        <div className='flex-1 mx-2 font-bold'>this is a long stream titiel</div>
                                    </div>
                                    <div className="m-auto mt-2 text-sm text-gray-400">
                                        167k views - 1 month ago
                                    </div>
                                </div>
                            </Link>
                        ))}


                    </div>
                </div>
            </div>

            <Footer />
        </div >
    )
}
