import Head from 'next/head'
import Footer from '../components/Footer';
import dynamic from 'next/dynamic';
import React from "react";
import { Alert } from '../components/alert.jsx';
import { useState, useEffect } from 'react';
import { FaUserAlt, FaPlusSquare, FaListUl, FaAffiliatetheme } from "react-icons/fa";

const Header = dynamic(() => import('../components/Header'), {
    ssr: false,
})

export default function My() {
    const [lists, setLists] = useState([]);

    const getList = async () => {
        let ret = [];
        for (let i = 0; i < 15; i++) {
            ret.push(i);
        }
        setLists(ret);
    }

    useEffect(() => {
        getList();
    }, [])



    return (
        <div className="min-h-screen bg-white" data-theme="bumblebee">
            <Head>
                <title>My rooms</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />

            <Alert />

            <div className="flex justify-center min-h-screen mx-auto w-5/6">
                <div className="overflow-x-auto">

                    {/* <h1 className='text-3xl font-bold'>My Rooms</h1> */}
                    <div className='flex m-auto mt-20'>
                        <div className='mt-1'><FaUserAlt size="2rem" /></div>
                        <div className='mx-2 text-3xl font-bold'>My Rooms</div>
                    </div>

                    <div className="divider"></div>

                    <table className="table mt-10">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Title</th>
                                <th>ticket</th>
                                <th>clients</th>
                                <th>created_at </th>
                                <th>remind</th>
                                <th>withdraw</th>
                                <th>entry</th>
                            </tr>
                        </thead>
                        <tbody>
                            {lists.map((item, index) => (
                                <tr>
                                    <th>{index + 1}</th>
                                    <td>Cy Ganderton</td>
                                    <td>Quality Control Specialist</td>
                                    <th>{index + 100}</th>
                                    <td>2023-01-01 11:12:13</td>
                                    <td><button className="btn btn-info btn-sm normal-case">notify</button></td>
                                    <td><button className="btn btn-success btn-sm normal-case">withdraw</button></td>
                                    <td><button className="btn btn-warning btn-sm normal-case">entry</button></td>
                                </tr>
                            ))}

                        </tbody>
                    </table>
                </div>

            </div>

            <Footer />
        </div >
    )
}
