import Head from 'next/head'
import Footer from '../components/Footer';
import dynamic from 'next/dynamic';
import React from "react";
import { Alert } from '../components/alert.jsx';

const Header = dynamic(() => import('../components/Header'), {
    ssr: false,
})

export default function My() {
    return (
        <div className="min-h-screen bg-white" data-theme="bumblebee">
            <Head>
                <title>Next.js Startup</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />

            <Alert />

            <div className="min-h-screen m-auto ml-10 mt-10">
                <div className="overflow-x-auto">
                    <table className="table">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Title</th>
                                <th>ticket</th>
                                <th>start</th>
                                <th>end</th>
                                <th>remind</th>
                                <th>created_at </th>
                            </tr>
                        </thead>
                        <tbody>
                            {/* row 1 */}
                            <tr>
                                <th>1</th>
                                <td>Cy Ganderton</td>
                                <td>Quality Control Specialist</td>
                                <td>2023-01-01 11:12:13</td>
                                <td>2023-01-01 11:12:13</td>
                                <td><button className="btn btn-sm">send notify</button></td>
                                <td>2023-01-01 11:12:13</td>
                            </tr>

                        </tbody>
                    </table>
                </div>

            </div>

            <Footer />
        </div >
    )
}
